# Site settings
title: Terry J. Brown
sub-title: Web Developer, Freelancer, Software Engineer
email: tjbrown90@gmail.com.com
description: > # this means to ignore newlines until "baseurl:"
  Web portfolio of Terry Brown. Created using github pages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.iamtjbrown.com" # the base hostname & protocol for your site
github_username:  tbrown90
linkedin_url: https://www.linkedin.com/in/tjbrown90

# Build settings
markdown: kramdown
